### ISSUE TITLE
502 Bad gateway on ubuntu installation 

### ISSUE THREAD

**Issue by jurquiza** [JBEI/edd#4]
No error on the installation however 502 Bad Gateway returned when requesting the webpage with 
http://edd.lvh.me/

However I do not get this issue when installed on macOS high sierra

**Comment by chimaerase** [comment]
Since EDD runs on Docker, it seems unlikely that the OS difference is to blame here.  You'll typically see this error any time that A) EDD is still coming up, e.g. following an install while it's applying database migrations or rebuilding its indexes, or B) When there's some configuration problem preventing the `edd` container from spinning up normally.  The error is returned by the `'nginx` proxy container when the `edd` container isn't responding.

My suggestion is to run `docker-compose logs -f edd` (or similar, depending on your configuration) to see the logs generated by the unresponsive `edd` container.

**Comment by jurquiza** [comment]
in a clean installation of macOS Mojave I now have the same issue, I'm trying to decipher the log something worth attention might be

postgres_1     | LOG:  incomplete startup packet
postgres_1     | FATAL:  password authentication failed for user "postgres"
postgres_1     | DETAIL:  Password does not match for user "postgres".
postgres_1     | 	Connection matched pg_hba.conf line 95: "host all all all md5"
edd_1          | psql: FATAL:  password authentication failed for user "postgres"
edd_1          | Initializing the database for first-time use …
edd_1          | psql: FATAL:  password authentication failed for user "postgres"
postgres_1     | FATAL:  password authentication failed for user "postgres"
postgres_1     | DETAIL:  Password does not match for user "postgres".
postgres_1     | 	Connection matched pg_hba.conf line 95: "host all all all md5"

**Comment by wmorrell** [comment]
That will happen if you re-run the `init-config` script after the database was already created with a previously generated password. Delete the postgres volume and re-launch to get a new volume using the correct password.

Check the existing volume names with `docker volume ls`. There will be one named `{Project Name}_pgdata`. Then run `docker volume rm {Project Name}_pgdata` to delete.

**Comment by jurquiza** [comment]
I tried that and it didn't work still producing generating similar errors. Even with the latest version. I will save the logs

**Comment by jurquiza** [comment]
[logs_edd.txt](https://github.com/JBEI/edd/files/2580289/logs_edd.txt)

**Comment by wmorrell** [comment]
Those logs are showing permission errors writing log files inside the containers. This should only happen when explicitly mounting a log directory with restricted file system permissions from the host to the container. There is not enough information here to diagnose the problem. At a minimum we would need to see the Docker image versions and the `docker-compose.override.yml` file in addition to the Docker log output.
