### ISSUE TITLE
Broken Tutorials/No Upload Feature

### ISSUE THREAD

**Issue by TylerReaganUCSD** [JBEI/edd#7]
Hello and thank you again for all your help so far. Now that I have managed to get what I believe is a functional deployment out, I am looking to test EDD's features. I navigated to https://public-edd.jbei.org/ and found all the tutorials to be broken (they do not have working mp4's or links). I also checked out https://edd.jbei.org/ but that does not seem to even allow me to login with my EDD credentials. I figured I could work things out myself but now I am not seeing an upload option on the public site when I login. Am I missing something, or is the feature to upload data to EDD not yet implemented? Thank you for your time and consideration.

**Comment by chimaerase** [comment]
Hi thanks for your patience and for your feedback!  Sounds like you are getting very close!

I think there are several problems happening here:

1) There is a known SSL certificate problem with the server we're using to host the tutorials, but they do work.  

I retested this morning, and the certificate problem causes a security prompt that I'm able to override.  For me, in Chrome, I get a prompt that "the connection is not private", but I can then click Advanced button, then click the link that says "proceed to downloads.jbei.org".  I will remind our IT team that this issue still needs to be resolved.

2) Each EDD instance is configured separately, so login credentials you set up on your test instance will not work on edd.jbei.org or public-edd.jbei.org.

The one exception to this is if you have Lawrence Berkeley Lab (LBL) login credentials, which we have configured to work on public-edd and edd.jbei.org.  Unless you have LBL credentials, you'll only be able to login into public-edd, and you'll need to self-register from the login screen or login in using a social media account.

3) You have to have edit permission on a study and you have to add lines to it before you can import data

Hopefully the tutorials will help to clarify this for you once you can access them.  I also recommend the paper, though the tool has evolved a little bit since both the paper and tutorials were published.  You also have to have edit permissions on a study to upload data to it, so you often won't see the import button for studies others have created.  If you want to change login and default study permissions in your EDD deployment, several settings are helpful for that.  Search for EDD_ALLOW_SIGNUP, EDD_ONLY_SUPERUSER_CREATE, EDD_DEFAULT_STUDY_READ_GROUPS under the edd/settings folder for some related documentation, then override them in your local.py.

-----

Once you do get to the import,  It's also worth mentioning that there are significant upgrades to the import tool in the pipeline.  The current tool works, but we've learned a lot from it as the tool has evolved, and it will be gradually replaced starting very soon.

**Comment by TylerReaganUCSD** [comment]
Thanks for getting back to me! The authentication clarification you provided actually answered one of my nagging questions so thank you. However, I had already been following the steps to override the security prompt and am still presented with an "ssl_server_cert_expired" page on all resources in the tutorial section:

![image](https://user-images.githubusercontent.com/41807470/61144439-7e284d00-a49a-11e9-8043-4412fda09579.png)

I was actually able to get all the videos from the tutorials off of your study's zip folder, but there exists no "Add New Study" button on the https://public-edd.jbei.org/ index page:

![image](https://user-images.githubusercontent.com/41807470/61144221-ed517180-a499-11e9-8d59-fcdeae7ebe1a.png)

I thought maybe I could just access things through https://edd.jbei.org/ since that is the domain used for the tutorial videos, but it informs me that signups are currently closed for use of that site. Perhaps something is wrong on my end, and if this is the case Ia m terribly sorry for using up your time. Hopefully my screenshot can provide some insights for you.

**Comment by chimaerase** [comment]
Hi, thanks for the additional feedback!  

On the SSL front, that's useful feedback.  I am not a sysadmin and that's not my area of expertise, but I suspect a proxy server configuration on your side of the fence may be affecting your ability to access the data before the problem on our end is addressed.  Sounds like you've found a workaround, so that's good.

As for study creation on public-edd, it's purposefully locked down by default as a security measure, controlled by one of the settings I mentioned.  There's an improvement in the pipeline to allow anyone to create studies by default, but to need additional permissions before they're allowed to share studies with others on the public instance.  The security concern we're avoiding here is allowing random Internet users to publish arbitrary data via EDD, and potentially use it for purposes other than those it is intended for.

I've granted you study creation permission on public-edd, and also attached a screenshot of how I accomplished that via the admin tools in case its of use to you.  From an administrator or "staff" account, you can access the admin tools via the "administration" link at the bottom of any page in EDD.

<img width="1010" alt="Screen Shot 2019-07-12 at 10 26 36 AM" src="https://user-images.githubusercontent.com/13455004/61146856-d9a10d80-a48f-11e9-8a39-cc9809ebf931.png">
