### ISSUE TITLE
Unable to launch EDD instance - connection refused

### ISSUE THREAD

**Issue by blenglee** [JBEI/edd#79]
I wanted to try to deploy a personal instance of EDD on my laptop (MACOS).
Here is what I did:
1) Install docker and git clone https://github.com/JBEI/edd.git
2) Next I did  docker pull jbei/edd-core
3) Then I run bin/init-config offline --deploy=dev
4) Based on https://edd-docs.jbei.org/, the quick start is to run docker compose up -d after the init-config offline --deploy=dev which I did.
However, I was not able to access edd.lvh.me from the browser
The message displayed when accessing http://edd.lvh.me:8000 is connection refused
or
Failed to connect to edd.lvh.me port 8000: Connection refused

5) docker status shows the containers are started and healthy

As a newbie, please let me know if there is any steps I had missed out, or if there is any configuration that I need to make.
Thank you for your help.

**Comment by wmorrell** [comment]
Hi @blenglee ,

Your problem is at step 2, where you `docker pull jbei/edd-core`. The `latest` tag pushed to Docker Hub is for version `2.6.7` from around 2.5 years ago. We stopped trying to do individual point releases with that version, and the code/libraries have shifted substantially since then. Using the current code with the old libraries in the Docker image will certainly break. It's definitely using a version of Django that is no longer supported, at least.

To build your own Docker image, do: 
```
DOCKER_BUILDKIT=1 docker build -t jbei/edd-core -f docker/edd/core/Dockerfile .
```

The docs should update to reflect this.

**Comment by blenglee** [comment]
Hi @wmorrell 
Thank you for your response.

Can you provide more details or pointers to the doc on how to set up my env to build my own docker image? 

And after building the docker image, what is the next step?

**Comment by wmorrell** [comment]
No additional environment setup is needed to build the image. After building, continue with `docker compose up -d` as in the documentation. Depending on whether the other supporting service containers are still up, it may take a minute to get a working app. You can watch the logs with `docker compose logs -f` and should see something like this when the web interface is up:

```
edd-http-1  | ********************************************************************************
edd-http-1  | Starting production appserver …
edd-http-1  | ********************************************************************************
edd-http-1  | + '[' -x /usr/local/bin/start_edd_process.sh ']'
edd-http-1  | + exec /usr/local/bin/start_edd_process.sh
edd-http-1  | + exec gosu edduser gunicorn -w 4 -b 0.0.0.0:8000 -k gthread --worker-tmp-dir /dev/shm --no-sendfile --forwarded-allow-ips '*' edd.wsgi:application
edd-http-1  | [2022-05-06 22:37:21 +0000] [7] [INFO] Starting gunicorn 20.1.0
edd-http-1  | [2022-05-06 22:37:21 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
edd-http-1  | [2022-05-06 22:37:21 +0000] [7] [INFO] Using worker: gthread
edd-http-1  | [2022-05-06 22:37:21 +0000] [1223] [INFO] Booting worker with pid: 1223
edd-http-1  | [2022-05-06 22:37:21 +0000] [1224] [INFO] Booting worker with pid: 1224
edd-http-1  | [2022-05-06 22:37:21 +0000] [1225] [INFO] Booting worker with pid: 1225
edd-http-1  | [2022-05-06 22:37:21 +0000] [1226] [INFO] Booting worker with pid: 1226
```

**Comment by blenglee** [comment]
Thank you. I will try it later today and update here.

**Comment by blenglee** [comment]
Thank you for your help.
I had followed your instruction above to build the docker image "edd-core".
I am not sure if the build aborts or this is the end of the build process:

⠿ postgres Pulled                                                                                                       
   ⠿ 27833a3ba0a5 Pull complete                                                                                          
   ⠿ ed00742830a6 Pull complete        
...
[+] Building 0.0s (0/0)  
"unable to prepare context: path "./docker/postgres/" not found".

Any reasons why?

Proceeding to run "docker compose up -d", I am able to launch the url http://edd.lvh.me.
However I noticed the following containers exited quickly after running for < 1 min during the startup time:
1) worker-1
2) http-1
3) websocket-1

Should these containers be in "running state"?

**Comment by blenglee** [comment]
docker compose logs -f output
[log.txt](https://github.com/JBEI/edd/files/9098739/log.txt)

**Comment by blenglee** [comment]
http-1 snippet shows:

Loading settings from /etc/edd …
Connection to postgres failed with connection to server at "postgres" , port xxx failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

...
Check SolrSearch[http://solr:8983/solr/users] OK
Check StudySearch[http://solr:8983/solr/studies][None] OK
Check SolrSearch[http://solr:8983/solr/measurement] OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column c.relispartition does not exist
LINE 5:                     WHEN c.relispartition THEN 'p'
                                 ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
...

**Comment by wmorrell** [comment]
It's difficult to diagnose exactly what's going wrong, without seeing the commands you're running, or your environment. I cannot debug this for you.

The output shown from the build looks like you're trying to use `docker compose build` instead of `docker build`, and are using a `docker-compose.yml` that is very out of date that references a Dockerfile for building a `postgres` container in `./docker/postgres/`. This will not work, as that image is no longer used, and the directory no longer exists. Mixing up current code with old Docker images will cause lots of problems, it's best to just build all the images directly and not pull from Docker Hub.

The output from `docker compose logs -f` is only showing the `ice_db` service. The output shown is normal.

The output from `http` is showing first a failure to connect to `postgres`, then is showing an error related to a failing query. The `relispartition` property was [introduced in Postgres 10](https://www.postgresql.org/docs/10/catalog-pg-class.html), and the version of Django used by EDD [does not support Postgres before 10](https://code.djangoproject.com/wiki/SupportedDatabaseVersions#PostgreSQL). So you're likely using an old Postgres 9.6, instead of a currently supported version.
