### ISSUE TITLE
How to bypass email verification?

### ISSUE THREAD

**Issue by blenglee** [JBEI/edd#81]
Hi,

At this point, I am able to bring up the containers and launch http://edd.lvh.me. I will like to know what is the proper way to bypass email verification in order to create account?

What I had done is by modifying server/edd/settings/auth.py with the following

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
ACCOUNT_EMAIL_VERIFICATION = "none"

and rebuild the image.

In the auth.py file, there was a comment line:
"# NOTE: override ACCOUNT_DEFAULT_HTTP_PROTOCOL in local.py with 'http' when in dev environment"
However I could not find the local.py, but I do see a directory with a name "local" and there is a __init__.py. 

Could you provide your directions?

Thanks again.

**Comment by wmorrell** [comment]
Having a `local.py` file makes a `local` settings module in Python, and having a directory named `local` with a `__init__.py` will do the same thing. The `local` module is loaded last in the overall `settings` module before it's passed to Django, so put all overrides there, instead of modifying the EDD code.

This is all described in the documentation: https://edd-docs.jbei.org/Configuration/
