### ISSUE TITLE
[Question]: Adding New Data and Metadata Fields

### ISSUE THREAD

**Issue by TylerReaganUCSD** [JBEI/edd#9]
Hi there. Thanks to your patience and help, I was able to get my own EDD instance up a few days ago and have been customizing it since then. I have now reached a point where I am looking to expand the fields for EDD data and metadata to fit my own internal use needs. I have been curating docs on the infrastructure of EDD to assist with this, but noticing its complexity I wanted to reach out and see if you had any advice or defined workflow that would allow me to make these modifications. To be more specific, my priority is modifying the fields related to Lines, Assays (by extension), and if possible, Measurement Values (my data is TPM rather than FPKM/RPKM). Thank you for any direction you can offer!

**Comment by chimaerase** [comment]
Good to hear that you have your EDD instance up and running!  By design, EDD allows you to define custom metadata fields by adding custom MetadataTypes using the Administration tools (Main -> Metadata Types).  EDD defines a number of built-in MetadataTypes, and also allows you to add your own using this interface.  You can also add custom units using a similar administration tool (that should resolve the TPM problem).  

While not wanting to outright forbid modifications to the code, I'd strongly caution you against that since EDD is still evolving, and you may find there's a significant amount of maintenance work over time to keep your modified code up as newer versions are released.

**Comment by wmorrell** [comment]
It's fine to modify the code. It's expected to modify the code. That's why we open-sourced it in the first place. I find that comment counter-productive.

The existing admin tools should be sufficient to do a lot of local customization; i.e. it's trivial to add a TPM measurement type to use instead of RPKM or FPKM. You can get to the admin tools by clicking the "Administration" link in the footer, when the logged in account is a superuser or "staff" account. If there are things that require code modifications, we would welcome pull requests to improve the code to fit your needs.

I will mention that with transcriptomic data specifically, there's some bits of the code that have (I think FPKM) values hard-coded into the display. Exporting data will show the correct values.

**Comment by TylerReaganUCSD** [comment]
Oh thanks that's super nifty and I must admit I am pretty embarrassed I missed it in the admin tools panel. I suppose I was too engrossed with the other options. Given these customization options, I think the only thing that would be missing would be the option to change Line fields. There are just a few fields I would like to add, but to be quite honest, if it would be too much a hassle to make modifications to the Line fields, the existing ones could be interpreted to fit my use case just fine. I am mostly curious as to how feasible modifications of this sort would be. 

Your code seems to fit more and more of what I need the more I discover of it, but seeing as I will probably be doing quite a bit of development work with the system, I will be sure to discuss pull requests if my institution allows me to do so. Thank you both for the feedback!

**Comment by chimaerase** [comment]
Thanks for the correction on this, wmorrell.. My comment was perhaps a bit carelessly worded.  I agree it's fine to modify the code, I'd just caution you against making big changes that don't get contributed back to the main repo, or against code changes that can be addressed using existing features.

**Comment by TylerReaganUCSD** [comment]
Oh of course. As I mentioned, an overwhelming majority of the existing code suites my needs very well. I am just looking to customize the fields associated with Lines to better match my data. If this seems like a task that would involve changing everything from the parsers/importers to the front end and models however, then I can see how that kind of change might not be a wise decision (or at least a time consuming one). I was really just trying to gauge the difficulty of this modification by asking for your opinion on solutions and also if you have any preexisting system like the admin console to achieve this change.
